server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: "11"

mybatis-plus:
  global-config:
    db-config:
      table-prefix: sys_
      #      使用数据库的id自增策略而不是mp的雪花算法
      id-type: auto
  #      开启mp日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


